module.exports = function(grunt) {
    
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        jshint: {
            all: ['**/*.js'],
            options: {
                ignores: ['node_modules/**/*.js', '**/*-autogenerated.js']
            }
        },
        jasmine_node: {
            options: {
                forceExit: true,
                match: '.',
                matchall: false,
                extensions: 'js',
                specNameMatcher: 'Tests'
            },
            all: ['test/']
        },
        browserify: {
            'web/public/javascripts/bundle-autogenerated.js': ['web/public/javascripts/**/*.js']
        },
        watch: {
            files: ['<%= jshint.all %>'],
            tasks: ['jshint', 'jasmine_node']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-jasmine-node');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-browserify');

    grunt.registerTask('test', ['jshint', 'jasmine_node']);
};
