#!/bin/bash

AWS_ACCESS_KEY=$1
AWS_SECRET_KEY=$2
touch .s3cfg
sed --in-place "s/access_key/access_key = $AWS_ACCESS_KEY/" .s3cfg
sed --in-place "s|secret_key|secret_key = $AWS_SECRET_KEY|" .s3cfg

s3cmd -c .s3cfg get s3://emil-project/config/config /tmp/config

while read line; do
	IFS=':' read -ra config <<< "$line"
	echo ${config[0]}
	echo ${config[1]}
	find -name '*.js-template' -exec sed -i 's/${config[0]}/${config[1]}/g' {} +
done </tmp/config

for file in $(find -name "*-template"); do
	dirname="${basename%/[^/]*}"
	filename="${basename:${#dirname} + 1}"
	mv "$file" "${dirname}/${filename}.js"
done

rm /tmp/config

apt-get -y install npm
npm install
npm install -g grunt-cli
apt-get -y install s3cmd
apt-get -y install nodejs-legacy
apt-get -y install graphicsmagick
apt-get -y install imagemagick
grunt browserify